# Generated by Django 3.2.3 on 2021-05-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationstatus',
            options={'verbose_name_plural': 'Notification Status'},
        ),
        migrations.RenameField(
            model_name='notificationstatus',
            old_name='read_status',
            new_name='is_read',
        ),
    ]
