# Generated by Django 3.2.3 on 2021-05-22 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_auto_20210522_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationstatus',
            old_name='user',
            new_name='recipient',
        ),
        migrations.AlterField(
            model_name='notification',
            name='receivers',
            field=models.ManyToManyField(related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
